### ISSUE TITLE
var.tags type mismatch

### ISSUE THREAD

**Issue by zimbatm** [terraform-aws-modules/terraform-aws-autoscaling#1]
The other modules accept a var.tags argument of type "map" that can be used to make sure all of the resources are tagged with the same things. This pattern is actually quite useful as it allows better discoverability in the AWS Console and to build various tools that can track all the resource usage for a specific terraform env.

Because this module "tags" variable has a type "list", it is not compatible with the other modules.

The reason why the type is different on this module is an implementation detail due to two different reasons:

(1) the autoscaling group is actually accepting a type list, which is why this is being used. and (2) the terraform interpolation language is not powerful enough to transform a map into a list of maps. I am assuming that all tags would be propagated at launch.

I think that for now it would make sense to rename the variable to "tags_list" to avoid ambiguity and allow to introduce a proper tags map once the language supports the transformation.

**Comment by antonbabenko** [comment]
Thank you for the first open issue since the official release! I think it took you just a couple of hours since the official announcement of the registry. 🥇

And it took me 7 days to reply to you. 🐌 🐌 🐌 🐌 🐌 🐌 🐌 

Regarding the issue... Unfortunately, this is the known difference inside AWS API. AWS API handles ASG tags differently than most of the other resources on AWS.

Variables defined in the module match Terraform arguments with very few exceptions (`lc_name`, `asg_name` and `launch_configuration`). This makes module very thin and transparent to users.

A good solution can be to use local variables or interpolation functions to convert a list into expected data structure inside the module, but I have not found the magic expression to do that yet. You are welcome to give it try and submit PR!

**Comment by nubbthedestroyer** [comment]
I think I found the magic expression.  Tell me what you think.
https://github.com/terraform-aws-modules/terraform-aws-autoscaling/pull/19
