### ISSUE TITLE
Scaling policies [question]

### ISSUE THREAD

**Issue by stephgosling** [terraform-aws-modules/terraform-aws-autoscaling#27]
Hi all,

First off let me say thanks for all of the hard work, I'm using this module a fair bit and it's saved me an awful lot of boilerplate. I just wanted to know if anyone was working on adding scaling policies? 

I've had a quick look around was able to more-or-less seamlessly integrate [Unifio's work](https://github.com/unifio/terraform-aws-asg/tree/master/policy) with the terraform-aws-autoscaling module, the only caveat being that you define `desired_capacity` here when it's technically optional: i.e. this module is scaling 'manually' versus 'dynamically'.

I just wanted to check whether scaling policies were in anyones sights already before I fork and use Unifio as inspiration; to avoid duplication of work and hacky code on my part.

Cheers,

Steph

**Comment by antonbabenko** [comment]
You are right that autoscaling policy should be rather easy to implement as part of this module.

The caveat you have discovered is currently a limitation of Terraform, which does not allow to specify variables inside `lifecycle` block. This means that we should have almost identical resources - one with lifecycle block ignoring changes in `desired_caparity` and another without.

It would be great if you can contribute support for autoscaling policies to this module.

**Comment by vkatsikaros** [comment]
@antonbabenko I would like to work on this issue.

My goal (to ensure we are on the same page): use the tf module `terraform-aws-modules/autoscaling/aws` to create ASGs with a [scaling policy](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scale-based-on-demand.html) and avoid being prompted to change the desired capacity if the scaling policy has changed the number of desired instances.

I understand that this is currently not doable. We can create an [autoscaling_policy tf resource](https://www.terraform.io/docs/providers/aws/r/autoscaling_policy.html) and attach it to the `this_autoscaling_group_name`. However, we `apply` or  `plan` while the desired capacity is different than the one defined in the ASG module(due to the scaling policy), the user will be prompted to apply/plan changes.

I would like to ask if you have any comments and if the above advice (1.5 year old now) still valid?

**Comment by misschak** [comment]
I solved this by doing   `desired_capacity = null`
https://stackoverflow.com/a/53203594/14532659

**Comment by goraxan** [comment]
@misschak I don't see how `desired_capacity = null` creates an autoscaling policy

**Comment by misschak** [comment]
> @misschak I don't see how `desired_capacity = null` creates an autoscaling policy

My bad, i wasn't explicit that I was solving the problem that @vkatsikaros faced. I've separately created an aws_autoscaling_schedule and attached to the asg (much as what @vkatsikaros has described) but `terraform apply` was always threatening to overwrite the desired_capacity as opposed to what was defined in the asg module, and "desired_capacity" is a mandatory variable in the asg module. I solved it by setting it to null (https://stackoverflow.com/a/53203594/14532659)

```
module "asg" {
  source  = "terraform-aws-modules/autoscaling/aws"
  version = "3.7.0"
  
  #other variables

  desired_capacity          = null
}

resource "aws_autoscaling_schedule" "pang_kang" {
  scheduled_action_name  = "asg-pangkang"
  desired_capacity       = 0
  autoscaling_group_name = module.asg.this_autoscaling_group_name
  recurrence             = "0 15 * * *"
}

resource "aws_autoscaling_schedule" "start_work" {
  scheduled_action_name  = "asg-start_work"
  desired_capacity       = 1
  autoscaling_group_name = module.asg.this_autoscaling_group_name
  recurrence             = "0 0 * * MON-FRI"
}
```

Hope this clarifies.

**Comment by goraxan** [comment]
That makes total sense now, thanks @misschak !
