### ISSUE TITLE
`ignore_changes` support

### ISSUE THREAD

**Issue by 1ambda** [terraform-aws-modules/terraform-aws-autoscaling#35]
Hi, I am using this module in our infra. Thanks a lot! 

However, our ECS instance count is increased or decrease based on ASG Policies
How should we handle the mismatch between terraform defined capacity (min, max, desired) and the actual capacity manipulated by ASG policies? 

For instance, in aws resource in terraform there is a `ignore_changes`.
Is there tip or trick we can apply? 

Thanks!

**Comment by antonbabenko** [comment]
This is sadly not supported by this module because it is not possible to specify variables inside `ignore_changes` lifecycle.

At the moment we don't know precisely what should be ignored and what should not be - different use-cases.

Normally, as far as I know, people fork this repository and maintain their own fork for this.

I believe an upcoming version of Terraform will allow variables in lifecycles and this module will have it too.

**Comment by rahulwa** [comment]
As searching on the internet shows nothing about it, made a gist to help the case: https://gist.github.com/rahulwa/91d63154d0238ef7316cbe4d3c6a8e9a
