### ISSUE TITLE
Lifecycle ignore?

### ISSUE THREAD

**Issue by luckytaxi** [terraform-aws-modules/terraform-aws-autoscaling#41]
I tried to ignore changes to userdata but terraform wants to recreate the AsG and launch configuration. What am I missing?

**Comment by antonbabenko** [comment]
It is not currently possible to do in Terraform 0.11.

As a workaround, you can create a launch configuration without using this module (add `ignore_changes` life-cycle to ignore changes in `user_data` argument) and pass name of this launch configuration to the module to handle auto scaling group.

This feature has been fixed in [v2.8.0](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/releases/tag/v2.8.0) since #45 was merged earlier today
